<?php
$tmp = array(
  array('recipe col-xl-8', 'template.php?page=recipe'),
  array('wine col-xl-4 masonrySizer', 'template.php?page=wine'),
  array('restaurant col-xl-8', 'template.php'),
  array('tip col-xl-4', 'template.php?page=tricks'),
);
$teasers = array();

foreach($tmp as $no => $t) {
    for($i=0;$i<10;$i++) {
        $teasers[] = array(
            'no' => $no,
            'class' => $t[0],
            'link' => $t[1],
        );
    }
}
shuffle($teasers);
shuffle($teasers);
shuffle($teasers);
shuffle($teasers);
shuffle($teasers);
?>
<section class="homePage">
    <header class="detailHeader parallax scroll" id="wineHeader">
        <div class="container">
            <h1>
                <span class="s1">Essen</span>
                <span class="s2">ist ein Bedürfnis</span>
                <span class="s3">Genießen</span>
                <span class="s4">ist eine Kunst!</span>
            </h1>
            <span class="source">
                François de La Rochefoucauld
            </span>
        </div>
    </header>
    <div class="container full">
        <ul class="row noSpace masonryRow">
            <?php foreach($teasers as $teaser) { ?>
                <li class="<?= $teaser['class']; ?> teaser masonryItem">
                    <a href="<?= $teaser['link']; ?>">
                        <span class="info">
                            <h2>
                                Lorem ipsum dolor
                            </h2>
                            <h3>Lorem ipsum dolor orem ipsum dolor</h3>
                            <p>
                                Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna...
                            </p>
                        </span>
                        <span class="label">
                            Rezept
                        </span>
                        <img src="<?= $_conf['baseURL'] ?>img/_dummy/teaser_<?= $teaser['no']; ?>.png" alt="1">
                    </a>
                </li>
            <?php } ?>
        </ul>
    </div>
</section>


<script src="https://cdnjs.cloudflare.com/ajax/libs/packery/2.1.1/packery.pkgd.js"></script>


<script>
    $(document).ready(function () {
        $('.masonryRow').packery({
            itemSelector: '.masonryItem',
            gutter: 0,
            masonry: {
                columnWidth: '.masonrySizer'
            }
        });
    })
</script>