<?php
  $cnt = array(
          'Geschmiedete Eisenpfannen',
          'tricks_pfanne.png',
          'Einmal eingebrannt, zeigen diese Pfannen beste Leitfähigkeit, „laufen“ genauso gut wie beschichtete Pfannen, aber ohne deren Empfindlichkeit gegen Kratzer und höhere Temperaturen. Eisen ist ein guter Wärmeleiter, der auf die Zu- und Abnahme von Kochhitze schnell und unmittelbar reagiert. '
  )
?>


<section class="tricksPage">
    <header class="detailHeader parallax scroll">
        <div class="container">
            <h1>
                <?= $cnt[0]; ?>
            </h1>
        </div>
    </header>

        <article class="row noSpace trick">
            <img src="<?= $_conf['baseURL'] ?>img/_dummy/<?= $cnt[1]; ?>" alt="1" class="col-xl-12">
            <article class="col-xl-12">
                <div>
                    <h2><?= $cnt[0]; ?></h2>
                    <p>
                        <?= $cnt[2]; ?>
                    </p>
                    <a href="#bla" target="_blank" class="btn btn-primary">Amazon</a>
                </div>
            </article>
        </article>
</section>
