<footer class="pageFooter clearfix">
    <div>
        <div class="copy">
            Copyright &copy; 2017 Florian Wessner - <a href="http://www.wesflo.de" target="_blank">wesflo</a>
        </div>
        <nav>
            <ul>
                <li>
                    <a href="#">Kontakt</a>
                </li>
                <li>
                    <a href="#">Impressum</a>
                </li>
            </ul>
        </nav>
    </div>
</footer>
