<?php
$nav = array(
    array(
        'label' => 'Rezepte',
        'href'  => 'template.php?page=recipe'
    ),
    array(
        'label' => 'Kategorien',
        'href'  => 'template.php'
    ),
    array(
        'label' => 'Zutaten',
        'href'  => 'template.php'
    ),
    array(
        'label' => 'Utensilien',
        'href'  => 'template.php'
    ),
    array(
        'label' => 'Tips & Tricks',
        'href'  => 'template.php?page=tricks'
    ),
    array(
        'label' => 'Weine',
        'href'  => 'template.php?page=wine'
    ),
/*    array(
        'label' => 'Tags',
        'href'  => '#'
    ),*/
);
?>
<header class="pageHeader">
    <nav class="mainNav">
        <ul class="clearfix">
            <li>
                <a href="<?= $_conf['baseURL'] ?>" class="logo">
                    <img src="<?= $_conf['baseURL'] ?>img/logo_head.png" alt="">
                </a>
            </li>
            <?php foreach ($nav as $item) { ?>
                <li>
                    <a href="<?= $item['href']; ?>">
                        <?= $item['label']; ?>
                    </a>
                </li>
            <?php } ?>
        </ul>
    </nav>
</header>